version: "3.4"

services:
    api:
        build:
          dockerfile: Dockerfile
          context: .
        ports:
          - "80:80"
        depends_on:
          - db
    db:
        environment:
            SA_PASSWORD: "Admin2admin"
            ACCEPT_EULA: "Y"
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        volumes:                #specify folder where to store database data
        - ./db-data/mssql       #whithout it, the data will be lost after container restart
        restart: always

        #"mcr.microsoft.com/mssql/server:2022-latest"